[package]
name = "rust-db"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
crc32_light = "0.1.2"
integer-encoding = "4.1.0"
log = "0.4.34"
thiserror = "2.0.20"

[dev-dependencies]
env_logger = "0.11.11"
quickcheck = "1.1.0"
quickcheck_macros = "1.2.0"
